### ISSUE TITLE
Running "croncoat --print-ini" resulted in the following error.

### ISSUE THREAD

**Issue by mwoolweaver** [MatthiasKauer/croncoat#10]
Installed croncoat via "sudo pip3 install croncoat" and then tried to use "croncoat --print-in" and received the following error: 

Traceback (most recent call last):
  File "/usr/local/bin/croncoat", line 7, in <module>
    from croncoat.scripts.ccscript import main
  File "/usr/local/lib/python3.5/dist-packages/croncoat/scripts/ccscript.py", line 17, in <module>
    from croncoat.cc.cronwrapper import CronWrapper
  File "/usr/local/lib/python3.5/dist-packages/croncoat/cc/cronwrapper.py", line 62
    print CronWrapper._ini_string(scriptname)

Software and hardware used

croncoat version: croncoat-0.4 subprocess32-3.5.3
pip version: pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5) 
OS : Raspbian GNU/Linux 9.6 (stretch)
Kernel: 4.14.94-v7+ #1193 SMP Tue Jan 22 15:34:30 GMT 2019 armv7l GNU/Linux
hardware: raspberry pi 3B

**Comment by mwoolweaver** [comment]
n

**Comment by MatthiasKauer** [comment]
Did this resolve itself @mwoolweaver ?

**Comment by mwoolweaver** [comment]
It was user error. . .
