### ISSUE TITLE
spawned processes confuse croncoat

### ISSUE THREAD

**Issue by petteway** [MatthiasKauer/croncoat#9]
I have a python script "processor" being executed by croncoat with -t 1h.  This script asyncronously spawns other long running processes "uploaders" using subprocess.Popen.  The "processor" being controlled by croncoat finishes relatively quickly.  The issue is that croncoat thinks it is still running because it has subprocess "uploaders" which have not finished.  So timeout occurs and it attempts to kill the "processor" process which is not running anymore and incorrectly errors out.

**Comment by MatthiasKauer** [comment]
Thank you for getting in touch.
That's an interesting usage. 
I don't know what is happening but more importantly I'm not sure I'm fully convinced this is unexpected behavior.
After all, the script is still running, no?

**Comment by petteway** [comment]
Well yes and no.  The uploaders are running and have their own error handling.  the "processor" script is not running.  So when the time is exceeded you get the error below.  The issue was that popen by default has the child process inheriting the stdout/stderr(stdout=None) so it appears to still be running when it isn't.  I've resolved my issue by stdout=subprocess.PIPE to not inherit and then I close them.  I now agree that there may not be anything needing to be fixed.  Thanks for the response.
  
Traceback (most recent call last):
 File "/usr/local/bin/croncoat", line 9, in <module>
   load_entry_point('croncoat==0.3.1', 'console_scripts', 'croncoat')()
 File "/usr/local/lib/python2.7/site-packages/croncoat/scripts/ccscript.py", line 108, in main
   cwrap.run()
 File "/usr/local/lib/python2.7/site-packages/croncoat/cc/cronwrapper.py", line 37, in run
   self.cmd.Run()
 File "/usr/local/lib/python2.7/site-packages/croncoat/cc/expiringcommand.py", line 73, in Run
   self.p.terminate()
 File "/usr/lib64/python2.7/subprocess.py", line 1567, in terminate
   self.send_signal(signal.SIGTERM)
 File "/usr/lib64/python2.7/subprocess.py", line 1562, in send_signal
   os.kill(self.pid, sig)
OSError: [Errno 3] No such process

**Comment by MatthiasKauer** [comment]
I'm afraid your understanding of this issue is bigger than mine at this point.
As you said, I don't know what should be adjusted in croncoat to accommodate such spawning behavior.

Side note: I released croncoat 0.4 recently.
